version: "3.8"
services:
  # Nginx servers
  nginx-backend:
    image: nginx
    container_name: karting-rm-nginx-backend-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./lb-backend.conf:/etc/nginx/nginx.conf
    networks:
      - karting-rm-backend-network
    depends_on:
      - spring1
      - spring2
      - spring3      
  nginx-frontend:
    image: nginx
    container_name: karting-rm-nginx-frontend-container
    restart: always
    ports:
      - 8070:8070
    volumes:
      - ./lb-frontend.conf:/etc/nginx/nginx.conf
    networks:
      - karting-rm-frontend-network
    depends_on:
      - react1
      - react2
      - react3
  mysql:
    container_name: karting-rm-mysql-container
    image: mysql:8.0
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - karting-rm-mysql-volume:/var/lib/mysql
    networks:
      - karting-rm-backend-network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bd-ev-3
    ports:
      - 3307:3306
  spring1:
    container_name: karting-rm-backend-container-1
    image: aguzmanusc/backend-tingeso
    ports:
      - 8091:8080
    environment:
      DB_HOST: karting-rm-mysql-container
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 1234
    networks:
      - karting-rm-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql
  spring2:
    container_name: karting-rm-backend-container-2
    image: aguzmanusc/backend-tingeso
    ports:
      - 8092:8080
    environment:
      DB_HOST: karting-rm-mysql-container
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 1234
    networks:
      - karting-rm-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql 
  spring3:
    container_name: karting-rm-backend-container-3
    image: aguzmanusc/backend-tingeso
    ports:
      - 8093:8080
    environment:
      DB_HOST: karting-rm-mysql-container
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 1234
    networks:
      - karting-rm-backend-network
    deploy:
      restart_policy:
        condition: on-failure
  react1:
    container_name: karting-rm-frontend-container-1
    image: aguzmanusc/nginx-fronted
    ports:
      - 3001:3000
    networks:
      - karting-rm-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react2:
    container_name: karting-rm-frontend-container-2
    image: aguzmanusc/nginx-fronted
    ports:
      - 3002:3000
    networks:
      - karting-rm-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react3:
    container_name: karting-rm-frontend-container-3
    image: aguzmanusc/nginx-fronted
    networks:
      - karting-rm-frontend-network
    ports:
      - 3003:3000
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  karting-rm-mysql-volume:
networks:
  karting-rm-frontend-network:
  karting-rm-backend-network: